{
 "title": "RT CM GRAPH",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cm_mac",
    "query": "show tag values from cablemodem with key=cm_mac"
   }
  ]
 },
 "panels": [
  {
   "title": "Ds Signal",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfDownChannelFrequency",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "docsIfDownChannelFrequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "select": [
      [
       { "params": [ "docsIfDownChannelPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "DS SNR",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfDownChannelFrequency",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "docsIfDownChannelFrequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "select": [
      [
       { "params": [ "docsIfSigQSignalNoise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "DS Micro Reflections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfDownChannelFrequency",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "docsIfDownChannelFrequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "select": [
      [
       { "params": [ "docsIfSigQMicroreflections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "DS CER",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfDownChannelFrequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "query": "SELECT 100*(non_negative_derivative(mean(\"docsIfSigQUncorrectables\"), 1s)/(non_negative_derivative(mean(\"docsIfSigQUncorrectables\"), 1s) + non_negative_derivative(mean(\"docsIfSigQCorrecteds\"), 1s) + non_negative_derivative(mean(\"docsIfSigQUnerroreds\"), 1s))) FROM \"cablemodem\" WHERE (\"cm_mac\" =~ /^$cm_mac$/) AND $timeFilter GROUP BY time(10s),\"docsIfDownChannelFrequency\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "DS FEC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfDownChannelFrequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "query": "SELECT 100*(non_negative_derivative(mean(\"docsIfSigQCorrecteds\"), 1s)/(non_negative_derivative(mean(\"docsIfSigQUncorrectables\"), 1s) + non_negative_derivative(mean(\"docsIfSigQCorrecteds\"), 1s) + non_negative_derivative(mean(\"docsIfSigQUnerroreds\"), 1s)))  FROM \"cablemodem\" WHERE (\"cm_mac\" =~ /^$cm_mac$/) AND $timeFilter GROUP BY time(10s),\"docsIfDownChannelFrequency\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "US SNR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "docsIfUpChannelFrequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usParams",
     "select": [
      [
       {
        "params": [
         "docsIf3CmtsCmUsStatusSignalNoise"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "US Signal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "docsIfUpChannelFrequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "select": [
      [
       { "params": [ "docsIf3CmStatusUsTxPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "US CM Rx Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "docsIfUpChannelFrequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "usParams",
     "select": [
      [
       { "params": [ "docsIf3CmtsCmUsStatusRxPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "US CER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "query": "SELECT 100*(non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusUncorrectables\"), 1s)/(non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusUncorrectables\"), 1s) + non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusCorrecteds\"), 1s) + non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusUnerroreds\"), 1s))) FROM \"usParams\" WHERE (\"cm_mac\" =~ /^$cm_mac$/) AND $timeFilter GROUP BY time(10s),\"docsIfUpChannelFrequency\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "US FEC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_docsIfUpChannelFrequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "query": "SELECT 100*(non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusCorrecteds\"), 1s)/(non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusUncorrectables\"), 1s) + non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusCorrecteds\"), 1s) + non_negative_derivative(mean(\"docsIf3CmtsCmUsStatusUnerroreds\"), 1s))) FROM \"usParams\" WHERE (\"cm_mac\" =~ /^$cm_mac$/) AND $timeFilter GROUP BY time(10s),\"docsIfUpChannelFrequency\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s) *8 FROM \"cablemodem\" WHERE (\"cm_mac\" =~ /^$cm_mac$/ AND \"ifName\" = 'cbl0') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "cbl0" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cablemodem",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s) *8 FROM \"cablemodem\" WHERE (\"cm_mac\" =~ /^$cm_mac$/ AND \"ifName\" = 'cbl0') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cm_mac", "operator": "=~", "value": "/^$cm_mac$/" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "cbl0" }
     ]
    }
   ]
  }
 ]
}